name: Flyway Migrations

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  flyway-migrate:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: mydb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set up Flyway Environment
        run: |
          echo "DATABASE_URL=postgresql://postgres:123@localhost:5432/CICD" > .env
          mkdir -p flyway/sql

      - name: Download Flyway CLI
        run: |
          curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.0.4/flyway-commandline-9.0.4-linux-x64.tar.gz | tar xvz
          sudo ln -s $(pwd)/flyway-9.0.4/flyway /usr/local/bin/flyway

      # 1. Backup database before migration
      - name: Backup Database (Before Migration)
        run: |
          mkdir -p backups
          export PGPASSWORD=123
          pg_dump -U postgres -h localhost -Fc -f backups/db_backup_$(date +%Y%m%d%H%M%S).dump CICD
        shell: bash

      # 2. Run Flyway Migrations
      - name: Run Flyway Migrate
        run: |
          flyway -url=jdbc:postgresql://localhost:5432/CICD -user=postgres -password=123 migrate

      # 3. Verify Migration Success
      - name: Verify Migration Success
        run: |
          if [ $? -ne 0 ]; then
            echo "Migration failed. Restoring the database."
            # Use the most recent backup to restore if migration fails
            BACKUP_FILE=$(ls -t backups | head -n 1)
            if [[ -f "backups/$BACKUP_FILE" ]]; then
              pg_restore -U postgres -h localhost -d CICD "backups/$BACKUP_FILE"
              echo "Database restored successfully."
              exit 1
            else
              echo "No backup file found for restoration."
              exit 1
            fi
          else
            echo "Migration completed successfully."
          fi
        shell: bash

      # 4. Backup database after migration (Optional)
      - name: Backup Database (After Migration)
        run: |
          mkdir -p backups
          export PGPASSWORD=123
          pg_dump -U postgres -h localhost -Fc -f backups/db_backup_after_migration_$(date +%Y%m%d%H%M%S).dump CICD
        shell: bash
