name: Prisma Migrations 

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  prisma-migrate:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: mydb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set up Prisma Environment
        run: |
          echo "DATABASE_URL=postgresql://postgres:123@localhost:5432/CICD?schema=public" > .env

      # 1. عمل نسخة احتياطية قبل الميجريشن
      - name: Backup Database (Before Migration)
        run: |
          mkdir -p backups
          export PGPASSWORD=123
          pg_dump -U postgres -h localhost -Fc -f backups/db_backup_$(date +%Y%m%d%H%M%S).dump CICD
        shell: bash

      # 2. تنفيذ الميجريشن باستخدام Prisma
      - name: Run Prisma Migrate
        run: npx prisma migrate deploy

      # 3. التحقق من نجاح الميجريشن
      - name: Verify Migration Success
        run: |
          if [ $? -ne 0 ]; then
            echo "Migration failed. Restoring the database."
            # Use the most recent backup to restore if migration fails
            BACKUP_FILE=$(ls -t backups | head -n 1)
            if [[ -f "backups/$BACKUP_FILE" ]]; then
              psql -U postgres -h localhost -d CICD -f "backups/$BACKUP_FILE"
              echo "Database restored successfully."
              exit 1
            else
              echo "No backup file found for restoration."
              exit 1
            fi
          else
            echo "Migration completed successfully."
          fi
        shell: bash

      # 4. عمل نسخة احتياطية بعد الميجريشن (اختياري)
      - name: Backup Database (After Migration)
        run: |
          mkdir -p backups
          export PGPASSWORD=123
          pg_dump -U postgres -h localhost -Fc -f backups/db_backup_after_migration_$(date +%Y%m%d%H%M%S).dump CICD
        shell: bash
